
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sports-center
    username: root
    password: 12345
  application:
    name: sports-center
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      
# Redis (Remote Dictionary Server) is a super-fast, in-memory database used for caching, session management, and real-time data processing.
