spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
      show-sql : true
  datasourceWriter:
    url: jdbc:mysql://localhost:3306/products
    username: root
    password: 12345

    hibernate:
      ddl-auto: update
    show-sql: true