version: '3.1'

services:
  sportscenter-mysql:
    image: mysql
    restart: always
    container_name: "sports-center-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - sports-center-mysql-data:/var/lib/mysql


volumes:

  sports-center-mysql-data:
